# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import PY_056 as module_0
import builtins as module_1


def test_case_0():
    bool_0 = True
    var_0 = module_0.classify_shipment_priority(
        bool_0, bool_0, bool_0, bool_0, bool_0, bool_0
    )
    assert var_0 == "urgent"


def test_case_1():
    bool_0 = False
    var_0 = module_0.classify_shipment_priority(
        bool_0, bool_0, bool_0, bool_0, bool_0, bool_0
    )
    assert var_0 == "normal"


def test_case_2():
    float_0 = 4729.22
    none_type_0 = None
    var_0 = module_0.classify_shipment_priority(
        float_0, float_0, float_0, float_0, float_0, none_type_0
    )
    assert var_0 == "high"


@pytest.mark.xfail(strict=True)
def test_case_3():
    none_type_0 = None
    module_0.classify_shipment_priority(
        none_type_0, none_type_0, none_type_0, none_type_0, none_type_0, none_type_0
    )


def test_case_4():
    bool_0 = False
    var_0 = module_0.classify_shipment_priority(
        bool_0, bool_0, bool_0, bool_0, bool_0, bool_0
    )
    assert var_0 == "normal"
    int_0 = 1685
    var_1 = module_0.classify_shipment_priority(
        bool_0, int_0, bool_0, bool_0, bool_0, var_0
    )
    assert var_1 == "low"


@pytest.mark.xfail(strict=True)
def test_case_5():
    int_0 = 286
    none_type_0 = None
    set_0 = set()
    module_0.classify_shipment_priority(
        int_0, int_0, none_type_0, int_0, set_0, none_type_0
    )


@pytest.mark.xfail(strict=True)
def test_case_6():
    int_0 = 180
    none_type_0 = None
    var_0 = module_0.classify_shipment_priority(
        int_0, int_0, int_0, none_type_0, none_type_0, int_0
    )
    assert var_0 == "normal"
    module_0.classify_shipment_priority(
        var_0, int_0, none_type_0, var_0, var_0, none_type_0
    )


def test_case_7():
    bool_0 = False
    none_type_0 = None
    str_0 = "silver"
    var_0 = module_0.classify_shipment_priority(
        bool_0, bool_0, bool_0, none_type_0, bool_0, str_0
    )
    assert var_0 == "normal"
    var_1 = module_0.classify_shipment_priority(
        bool_0, bool_0, bool_0, bool_0, bool_0, bool_0
    )
    assert var_1 == "normal"
    int_0 = 1685
    var_2 = module_0.classify_shipment_priority(
        bool_0, int_0, bool_0, bool_0, bool_0, var_1
    )
    assert var_2 == "low"


@pytest.mark.xfail(strict=True)
def test_case_8():
    bool_0 = True
    none_type_0 = None
    str_0 = "gold"
    var_0 = module_0.classify_shipment_priority(
        bool_0, bool_0, bool_0, none_type_0, bool_0, str_0
    )
    assert var_0 == "high"
    module_1.object(*var_0)


def test_case_9():
    int_0 = 20
    var_0 = module_0.classify_shipment_priority(
        int_0, int_0, int_0, int_0, int_0, int_0
    )
    assert var_0 == "high"
    var_1 = module_1.object()
