# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import PY_043 as module_0


def test_case_0():
    none_type_0 = None
    with pytest.raises(ValueError):
        module_0.validate_fillna_kwargs(none_type_0, none_type_0)


def test_case_1():
    float_0 = -3326.0437
    with pytest.raises(ValueError):
        module_0.validate_fillna_kwargs(float_0, float_0)


def test_case_2():
    none_type_0 = None
    bytes_0 = b"\x95\xbaN^\x9f\xc4g\xefA\x8f\x8a\xa4\xa8"
    with pytest.raises(ValueError):
        module_0.validate_fillna_kwargs(none_type_0, bytes_0)


def test_case_3():
    bytes_0 = b"L0&\x84\xc3=\xe6\x0e\xce\xdb\xcd\xcf\x99g\xa9Q\xae#\xb8\x06"
    none_type_0 = None
    var_0 = module_0.validate_fillna_kwargs(bytes_0, none_type_0)


def test_case_4():
    float_0 = 4913.701692190269
    none_type_0 = None
    var_0 = module_0.validate_fillna_kwargs(float_0, none_type_0, none_type_0)
    with pytest.raises(ValueError):
        module_0.validate_fillna_kwargs(var_0, var_0, var_0)


def test_case_5():
    bool_0 = False
    tuple_0 = (bool_0,)
    none_type_0 = None
    with pytest.raises(TypeError):
        module_0.validate_fillna_kwargs(tuple_0, none_type_0, tuple_0)
