# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import PY_049 as module_0


def test_case_0():
    bytes_0 = b"3;\x83iN\x82fU\x04\r"
    list_0 = [bytes_0, bytes_0, bytes_0]
    var_0 = module_0.merge_intervals(list_0)


def test_case_1():
    none_type_0 = None
    var_0 = module_0.merge_intervals(none_type_0)


def test_case_2():
    bytes_0 = b"\xdeU\xe9\x81\x911\xbbf|\xeeK*\x8a\xbae\x08\x15|\xc6"
    list_0 = [bytes_0, bytes_0, bytes_0]
    var_0 = module_0.merge_intervals(list_0)
    none_type_0 = None
    var_1 = module_0.merge_intervals(none_type_0)


def test_case_3():
    str_0 = "^m9@t5;K`B_O?7;hx"
    bool_0 = False
    str_1 = "\r`]^VUa"
    dict_0 = {str_0: bool_0, str_0: bool_0, str_1: str_1}
    var_0 = module_0.merge_intervals(dict_0)
