# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import PY_048 as module_0


def test_case_0():
    none_type_0 = None
    module_0.act(
        none_type_0, none_type_0, none_type_0, none_type_0, deterministic=none_type_0
    )


def test_case_1():
    bytes_0 = b'"Az\xc4;\xe8\xdb\x15H\x99\xe0\x8bh'
    module_0.act(bytes_0, bytes_0, bytes_0, bytes_0, bytes_0, bytes_0)
