# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import PY_066 as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    int_0 = -2653
    module_0.getitem_block(int_0, int_0)


@pytest.mark.xfail(strict=True)
def test_case_1():
    none_type_0 = None
    module_0.getitem_block(none_type_0)


@pytest.mark.xfail(strict=True)
def test_case_2():
    tuple_0 = ()
    module_0.getitem_block(tuple_0, tuple_0)
