# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import PY_071 as module_0


def test_case_0():
    dict_0 = {}
    var_0 = module_0.rehydrate_skeleton_class(dict_0, dict_0)


@pytest.mark.xfail(strict=True)
def test_case_1():
    none_type_0 = None
    module_0.rehydrate_skeleton_class(none_type_0, none_type_0)


@pytest.mark.xfail(strict=True)
def test_case_2():
    none_type_0 = None
    bool_0 = True
    str_0 = '`"!^_\tpk'
    dict_0 = {str_0: none_type_0, bool_0: bool_0, bool_0: bool_0}
    module_0.rehydrate_skeleton_class(none_type_0, dict_0)
