# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import PY_055 as module_0
import builtins as module_1


def test_case_0():
    none_type_0 = None
    int_0 = -4154
    with pytest.raises(ValueError):
        module_0.normalize_path(none_type_0, strict=int_0)


@pytest.mark.xfail(strict=True)
def test_case_1():
    bool_0 = True
    module_0.normalize_path(bool_0, strict=bool_0, allow_empty=bool_0)


def test_case_2():
    str_0 = "3"
    var_0 = module_0.normalize_path(str_0, str_0)
    assert var_0 == "/3/3"


def test_case_3():
    str_0 = "3"
    var_0 = module_0.normalize_path(str_0)
    assert var_0 == "/3"
    var_1 = module_0.normalize_path(str_0, str_0)
    assert var_1 == "/3/3"
    var_2 = module_0.normalize_path(var_1)
    assert var_2 == "/3/3"


@pytest.mark.xfail(strict=True)
def test_case_4():
    str_0 = "3"
    var_0 = module_0.normalize_path(str_0)
    assert var_0 == "/3"
    var_1 = module_0.normalize_path(var_0, var_0)
    assert var_1 == "/3"
    var_2 = module_0.normalize_path(str_0)
    assert var_2 == "/3"
    var_3 = module_0.normalize_path(str_0, str_0)
    assert var_3 == "/3/3"
    module_1.object(*var_0)


def test_case_5():
    str_0 = ".i/ $@e0,eT\rq!"
    none_type_0 = None
    var_0 = module_0.normalize_path(str_0, strict=none_type_0, allow_empty=str_0)
    assert var_0 == "/.i/ $@e0,eT\rq!"
    var_1 = module_0.normalize_path(none_type_0, allow_empty=str_0)
    assert var_1 == ""
    object_0 = module_1.object()


def test_case_6():
    str_0 = "."
    none_type_0 = None
    var_0 = module_0.normalize_path(str_0, allow_empty=none_type_0)
    assert var_0 == "/"


@pytest.mark.xfail(strict=True)
def test_case_7():
    str_0 = "../ $@e0,eT\rq!"
    var_0 = module_0.normalize_path(str_0, str_0)
    assert var_0 == "/../ $@e0,eT\rq!/../ $@e0,eT\rq!"
    object_0 = module_1.object()
    var_1 = module_0.normalize_path(var_0)
    assert var_1 == "/../ $@e0,eT\rq!/../ $@e0,eT\rq!"
    object_1 = module_1.object()
    module_1.object(*str_0)


@pytest.mark.xfail(strict=True)
def test_case_8():
    str_0 = "../$@e0,eT\rq!"
    var_0 = module_0.normalize_path(str_0, str_0)
    assert var_0 == "/../$@e0,eT\rq!/../$@e0,eT\rq!"
    object_0 = module_1.object()
    var_1 = module_0.normalize_path(var_0, allow_empty=var_0)
    assert var_1 == "/../$@e0,eT\rq!/../$@e0,eT\rq!"
    var_2 = module_0.normalize_path(var_1, strict=var_0)
    assert var_2 == "/$@e0,eT\rq!"
    var_3 = module_0.normalize_path(var_0)
    assert var_3 == "/../$@e0,eT\rq!/../$@e0,eT\rq!"
    object_1 = module_1.object()
    module_1.object(*str_0)
