# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import PY_043 as module_0


def test_case_0():
    bytes_0 = b"\x894\x12\xa1"
    none_type_0 = None
    module_0.get_actions(
        bytes_0, bytes_0, bytes_0, none_type_0, none_type_0, deterministic=bytes_0
    )


def test_case_1():
    int_0 = 868
    dict_0 = {}
    module_0.get_actions(int_0, dict_0, int_0, int_0, dict_0, int_0)
