# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import PY_080 as module_0


def test_case_0():
    bool_0 = False
    list_0 = [bool_0, bool_0, bool_0, bool_0, bool_0, bool_0]
    var_0 = module_0.three_sum(list_0)


@pytest.mark.xfail(strict=True)
def test_case_1():
    none_type_0 = None
    module_0.three_sum(none_type_0)


def test_case_2():
    bool_0 = True
    list_0 = [bool_0, bool_0, bool_0, bool_0, bool_0, bool_0]
    var_0 = module_0.three_sum(list_0)


def test_case_3():
    int_0 = -2337
    list_0 = [int_0, int_0, int_0]
    var_0 = module_0.three_sum(list_0)


@pytest.mark.xfail(strict=True)
def test_case_4():
    bool_0 = True
    int_0 = -292
    list_0 = [bool_0, bool_0, int_0, bool_0]
    var_0 = module_0.three_sum(list_0)
    bool_1 = False
    module_0.three_sum(bool_1)
