# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import PY_068 as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    bytes_0 = b"Lt\x12\xb0\x0f(pj{v4W"
    module_0.check_is_max_context(bytes_0, bytes_0, bytes_0)


@pytest.mark.xfail(strict=True)
def test_case_1():
    list_0 = []
    var_0 = module_0.check_is_max_context(list_0, list_0, list_0)
    assert var_0 is False
    str_0 = "3Qbi\tz-IJk#\x0c"
    module_0.check_is_max_context(str_0, str_0, str_0)
