# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import PY_083 as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    complex_0 = 66.365 + 2552.611385j
    module_0.bind(complex_0)
