# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import PY_054 as module_0


def test_case_0():
    str_0 = "^'>Y\\J#"
    dict_0 = {str_0: str_0, str_0: str_0, str_0: str_0, str_0: str_0}
    var_0 = module_0.build_query_string(dict_0, exclude_none=dict_0)
    assert var_0 == "^'>Y\\J#=^'>Y\\J#"


@pytest.mark.xfail(strict=True)
def test_case_1():
    bool_0 = True
    module_0.build_query_string(bool_0, exclude_none=bool_0, encode_spaces=bool_0)


def test_case_2():
    bool_0 = False
    tuple_0 = (bool_0, bool_0)
    none_type_0 = None
    dict_0 = {bool_0: tuple_0, bool_0: none_type_0, tuple_0: bool_0}
    var_0 = module_0.build_query_string(dict_0, bool_0)
    assert var_0 == "(False, False)=false"


@pytest.mark.xfail(strict=True)
def test_case_3():
    int_0 = -2172
    int_1 = 544
    dict_0 = {int_0: int_0, int_0: int_0, int_0: int_1, int_0: int_1}
    none_type_0 = None
    var_0 = module_0.build_query_string(dict_0, none_type_0, none_type_0, none_type_0)
    assert var_0 == "-2172=544"
    var_1 = module_0.build_query_string(dict_0)
    assert var_1 == "-2172=544"
    none_type_1 = None
    module_0.build_query_string(none_type_1)


@pytest.mark.xfail(strict=True)
def test_case_4():
    bool_0 = True
    tuple_0 = (bool_0, bool_0)
    dict_0 = {tuple_0: bool_0}
    var_0 = module_0.build_query_string(dict_0, encode_spaces=dict_0)
    assert var_0 == "(True, True)=true"
    int_0 = -2172
    int_1 = 544
    dict_1 = {int_0: int_0, int_0: int_0, int_0: int_1, int_0: int_1}
    var_1 = module_0.build_query_string(dict_1)
    assert var_1 == "-2172=544"
    bool_1 = True
    list_0 = [dict_0, bool_1, dict_1, dict_1]
    module_0.build_query_string(var_0, bool_0, encode_spaces=list_0)


@pytest.mark.xfail(strict=True)
def test_case_5():
    bool_0 = False
    tuple_0 = (bool_0, bool_0)
    dict_0 = {tuple_0: bool_0, tuple_0: tuple_0}
    var_0 = module_0.build_query_string(dict_0, encode_spaces=dict_0)
    assert var_0 == "(False, False)=False&(False, False)=False"
    module_0.build_query_string(var_0)


def test_case_6():
    bool_0 = False
    tuple_0 = (bool_0, bool_0)
    dict_0 = {tuple_0: bool_0, tuple_0: tuple_0}
    var_0 = module_0.build_query_string(dict_0, encode_spaces=bool_0)
    assert var_0 == "(False, False)=False&(False, False)=False"
    none_type_0 = None
    var_1 = module_0.build_query_string(dict_0, encode_spaces=tuple_0)
    assert var_1 == "(False, False)=False&(False, False)=False"
    dict_1 = {bool_0: dict_0, bool_0: none_type_0, tuple_0: bool_0}
    var_2 = module_0.build_query_string(dict_1, bool_0)
    assert var_2 == "(False, False)=false"


@pytest.mark.xfail(strict=True)
def test_case_7():
    bool_0 = False
    tuple_0 = (bool_0, bool_0)
    dict_0 = {tuple_0: bool_0, tuple_0: tuple_0}
    var_0 = module_0.build_query_string(dict_0, encode_spaces=bool_0)
    assert var_0 == "(False, False)=False&(False, False)=False"
    int_0 = 468
    none_type_0 = None
    none_type_1 = None
    var_1 = module_0.build_query_string(dict_0, encode_spaces=tuple_0)
    assert var_1 == "(False, False)=False&(False, False)=False"
    int_1 = 41
    dict_1 = {int_1: dict_0, bool_0: none_type_1, tuple_0: int_1}
    var_2 = module_0.build_query_string(dict_1, bool_0, none_type_0, int_0)
    assert var_2 == "41={(False,+False):+(False,+False)}&False=&(False, False)=41"
    var_3 = module_0.build_query_string(dict_1, bool_0)
    assert var_3 == "41={(False,+False):+(False,+False)}&(False, False)=41"
    list_0 = [var_3, none_type_0, int_0, dict_1]
    module_0.build_query_string(list_0)
