# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import PY_064 as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    bytes_0 = b"\x894\x12\xa1"
    none_type_0 = None
    module_0.detect_anomaly(
        bytes_0, bytes_0, bytes_0, none_type_0, none_type_0, reset_on_recovery=bytes_0
    )


def test_case_1():
    bool_0 = False
    set_0 = {bool_0, bool_0, bool_0, bool_0, bool_0}
    int_0 = -7
    var_0 = module_0.detect_anomaly(set_0, int_0, bool_0, bool_0, bool_0, bool_0, set_0)


@pytest.mark.xfail(strict=True)
def test_case_2():
    bytes_0 = b"\x894\x12\xa1"
    none_type_0 = None
    module_0.detect_anomaly(bytes_0, bytes_0, bytes_0, bytes_0, none_type_0, bytes_0)


def test_case_3():
    bool_0 = False
    set_0 = {bool_0, bool_0, bool_0, bool_0, bool_0}
    set_1 = set()
    var_0 = module_0.detect_anomaly(
        set_0, bool_0, bool_0, bool_0, bool_0, bool_0, set_1
    )


@pytest.mark.xfail(strict=True)
def test_case_4():
    bool_0 = False
    tuple_0 = (bool_0,)
    var_0 = module_0.detect_anomaly(tuple_0, bool_0, bool_0, tuple_0, tuple_0)
    str_0 = "xtn5z9"
    none_type_0 = None
    module_0.detect_anomaly(str_0, str_0, none_type_0, none_type_0, none_type_0)


@pytest.mark.xfail(strict=True)
def test_case_5():
    bytes_0 = b"k~t\xc4\x18"
    bool_0 = False
    var_0 = module_0.detect_anomaly(bytes_0, bool_0, bool_0, bytes_0, bool_0, bytes_0)
    none_type_0 = None
    str_0 = "k`Dm]"
    module_0.detect_anomaly(bool_0, none_type_0, str_0, bytes_0, str_0)


def test_case_6():
    bool_0 = True
    tuple_0 = (bool_0,)
    int_0 = -107
    str_0 = "e>zThf\reyFMs("
    var_0 = module_0.detect_anomaly(tuple_0, bool_0, int_0, bool_0, str_0)
