# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import PY_058 as module_0
import builtins as module_1


def test_case_0():
    int_0 = 70
    var_0 = module_0.compute_loan_eligibility(int_0, int_0, int_0, int_0, int_0, int_0)
    object_0 = module_0.compute_loan_eligibility(
        int_0, var_0, var_0, var_0, var_0, var_0
    )


def test_case_1():
    int_0 = 70
    var_0 = module_0.compute_loan_eligibility(int_0, int_0, int_0, int_0, int_0, int_0)


@pytest.mark.xfail(strict=True)
def test_case_2():
    none_type_0 = None
    module_0.compute_loan_eligibility(
        none_type_0, none_type_0, none_type_0, none_type_0, none_type_0, none_type_0
    )


@pytest.mark.xfail(strict=True)
def test_case_3():
    int_0 = 2198
    none_type_0 = None
    var_0 = module_0.compute_loan_eligibility(
        int_0, none_type_0, none_type_0, int_0, int_0, int_0
    )
    assert var_0 is False
    str_0 = "u!N8(?D\"'V24H7H}5P"
    list_0 = [str_0]
    object_0 = module_1.object()
    none_type_1 = None
    module_0.compute_loan_eligibility(
        str_0, str_0, list_0, object_0, none_type_1, str_0
    )


def test_case_4():
    int_0 = 70
    var_0 = module_0.compute_loan_eligibility(int_0, int_0, int_0, int_0, int_0, int_0)
    var_1 = module_0.compute_loan_eligibility(var_0, var_0, int_0, var_0, var_0, var_0)
    int_1 = -887
    int_2 = -750
    var_2 = module_0.compute_loan_eligibility(var_0, int_2, int_2, int_0, var_1, var_0)
    var_3 = module_0.compute_loan_eligibility(var_1, var_0, var_1, int_0, int_1, var_0)
    int_3 = 1054
    var_4 = module_0.compute_loan_eligibility(int_3, int_3, int_0, var_0, int_0, int_0)
    assert var_4 is True
    var_5 = module_0.compute_loan_eligibility(int_3, int_3, int_3, int_3, int_0, int_3)
    assert var_5 is True


@pytest.mark.xfail(strict=True)
def test_case_5():
    int_0 = 18
    var_0 = module_0.compute_loan_eligibility(int_0, int_0, int_0, int_0, int_0, int_0)
    int_1 = 872
    none_type_0 = None
    var_1 = module_0.compute_loan_eligibility(var_0, int_1, var_0, int_0, int_0, int_0)
    assert var_1 is True
    int_2 = 883
    var_2 = module_0.compute_loan_eligibility(int_2, var_1, int_2, var_0, int_2, var_0)
    var_3 = module_0.compute_loan_eligibility(int_2, int_2, int_2, int_2, int_0, int_2)
    assert var_3 is True
    var_4 = module_0.compute_loan_eligibility(
        var_0, none_type_0, int_1, var_1, var_1, var_0
    )
    assert var_4 is False
    module_1.object(**var_3)


@pytest.mark.xfail(strict=True)
def test_case_6():
    int_0 = 59
    var_0 = module_0.compute_loan_eligibility(int_0, int_0, int_0, int_0, int_0, int_0)
    var_1 = module_0.compute_loan_eligibility(var_0, var_0, int_0, var_0, var_0, var_0)
    var_2 = module_0.compute_loan_eligibility(int_0, var_0, var_0, var_1, var_1, var_0)
    int_1 = -887
    int_2 = -4333
    var_3 = module_0.compute_loan_eligibility(var_0, int_2, int_2, int_0, var_1, var_0)
    var_4 = module_1.object()
    int_3 = 1013
    var_5 = module_0.compute_loan_eligibility(int_3, int_3, int_0, var_0, int_0, int_0)
    assert var_5 is True
    var_6 = module_0.compute_loan_eligibility(int_3, int_3, int_3, int_3, int_0, var_3)
    assert var_6 is False
    object_0 = module_1.object()
    var_7 = module_0.compute_loan_eligibility(var_6, var_3, int_1, var_5, var_3, var_6)
    str_0 = "9x^+Wb)L\x0cEVD6sf;DLE"
    var_8 = module_0.compute_loan_eligibility(int_1, var_4, var_3, int_3, int_3, int_1)
    assert var_8 is False
    dict_0 = {var_7: int_1, str_0: var_4}
    module_0.compute_loan_eligibility(str_0, var_7, int_1, dict_0, dict_0, var_4)


@pytest.mark.xfail(strict=True)
def test_case_7():
    int_0 = 29
    none_type_0 = None
    var_0 = module_0.compute_loan_eligibility(
        int_0, int_0, int_0, int_0, int_0, none_type_0
    )
    int_1 = 753
    var_1 = module_0.compute_loan_eligibility(
        int_1, var_0, var_0, int_1, int_1, none_type_0
    )
    var_2 = module_0.compute_loan_eligibility(
        var_0, var_0, var_1, none_type_0, int_0, none_type_0
    )
    var_3 = module_0.compute_loan_eligibility(var_2, var_2, var_1, int_1, var_1, var_0)
    int_2 = 656
    var_4 = module_0.compute_loan_eligibility(
        int_2, int_1, none_type_0, int_1, int_1, int_2
    )
    assert var_4 is False
    var_5 = module_0.compute_loan_eligibility(int_2, int_2, int_0, var_3, int_0, int_0)
    assert var_5 is False
    var_6 = module_0.compute_loan_eligibility(
        var_4, var_3, var_5, none_type_0, var_5, var_3
    )
    var_7 = module_0.compute_loan_eligibility(
        int_0, var_3, int_0, none_type_0, var_5, var_3
    )
    var_8 = module_0.compute_loan_eligibility(int_2, int_2, int_2, int_2, int_0, int_2)
    assert var_8 is False
    var_9 = module_0.compute_loan_eligibility(int_0, int_2, int_0, var_1, int_0, var_1)
    bytes_0 = b'\xc3"YK\xc9\x80\rk&U\xa4'
    object_0 = module_1.object()
    var_10 = module_0.compute_loan_eligibility(
        bytes_0, var_1, var_4, var_4, var_4, var_0
    )
    bool_0 = True
    bool_1 = False
    module_0.compute_loan_eligibility(var_0, bool_1, object_0, bool_0, bytes_0, bytes_0)


def test_case_8():
    int_0 = 60
    int_1 = 603
    var_0 = module_0.compute_loan_eligibility(int_1, int_1, int_0, int_1, int_0, int_0)
    assert var_0 == 60
    var_1 = module_0.compute_loan_eligibility(int_1, int_1, int_1, int_1, int_0, int_1)
    object_0 = module_1.object()
    bool_0 = False
    int_2 = -5573
    set_0 = {bool_0}
    bool_1 = False
    var_2 = module_0.compute_loan_eligibility(int_2, set_0, set_0, bool_1, int_1, set_0)
    assert var_2 is False


def test_case_9():
    int_0 = 18
    none_type_0 = None
    var_0 = module_0.compute_loan_eligibility(
        int_0, int_0, int_0, int_0, int_0, none_type_0
    )
    int_1 = 824
    object_0 = module_1.object()
    none_type_1 = None
    var_1 = module_0.compute_loan_eligibility(
        int_1, none_type_1, int_0, int_1, int_1, none_type_1
    )
    assert var_1 is False
    var_2 = module_0.compute_loan_eligibility(
        int_1, int_1, int_1, int_0, int_0, object_0
    )
    assert var_2 is True
    int_2 = 883
    var_3 = module_0.compute_loan_eligibility(int_2, int_2, int_0, var_2, int_0, int_0)
    assert var_3 is True
    var_4 = module_0.compute_loan_eligibility(
        object_0, none_type_1, int_1, var_2, var_1, int_0
    )
    assert var_4 is False


@pytest.mark.xfail(strict=True)
def test_case_10():
    int_0 = 29
    int_1 = 656
    var_0 = module_0.compute_loan_eligibility(int_1, int_1, int_1, int_1, int_0, int_1)
    assert var_0 is False
    bytes_0 = b'\xc3"YK\xc9\x80\rk&U\xa4'
    object_0 = module_1.object()
    bool_0 = False
    module_0.compute_loan_eligibility(object_0, int_1, int_0, int_0, bytes_0, bool_0)


def test_case_11():
    int_0 = 60
    int_1 = 603
    var_0 = module_0.compute_loan_eligibility(int_1, int_1, int_0, int_1, int_0, int_0)
    assert var_0 == 60
    object_0 = module_1.object()
    bool_0 = False
    int_2 = -5573
    set_0 = {bool_0}
    var_1 = module_0.compute_loan_eligibility(int_2, set_0, set_0, bool_0, int_1, set_0)
    assert var_1 is False


@pytest.mark.xfail(strict=True)
def test_case_12():
    int_0 = 25
    none_type_0 = None
    var_0 = module_0.compute_loan_eligibility(
        int_0, int_0, int_0, int_0, int_0, none_type_0
    )
    int_1 = 767
    var_1 = module_0.compute_loan_eligibility(
        int_1, var_0, var_0, int_1, int_1, none_type_0
    )
    var_2 = module_0.compute_loan_eligibility(var_1, int_1, var_1, int_0, int_0, int_1)
    assert var_2 is True
    var_3 = module_0.compute_loan_eligibility(
        var_0, var_0, var_1, none_type_0, var_2, none_type_0
    )
    var_4 = module_0.compute_loan_eligibility(var_3, var_3, var_2, var_3, var_0, var_1)
    var_5 = module_0.compute_loan_eligibility(var_2, var_2, var_1, int_1, var_1, var_0)
    int_2 = 594
    var_6 = module_0.compute_loan_eligibility(
        int_2, int_1, none_type_0, int_1, int_1, int_2
    )
    assert var_6 is False
    var_7 = module_0.compute_loan_eligibility(int_2, int_2, int_0, var_2, int_0, int_0)
    assert var_7 is False
    var_8 = module_0.compute_loan_eligibility(int_2, int_2, int_2, int_2, int_0, int_2)
    var_9 = module_0.compute_loan_eligibility(int_0, var_6, var_5, int_2, var_8, var_8)
    var_10 = module_0.compute_loan_eligibility(int_0, int_2, int_0, var_1, int_0, var_1)
    bytes_0 = b'\xc3"YK\xc9\x80\rk&U\xa4'
    object_0 = module_1.object()
    var_11 = module_0.compute_loan_eligibility(
        bytes_0, var_1, var_6, var_6, var_6, var_0
    )
    module_0.compute_loan_eligibility(var_8, var_11, var_0, var_0, bytes_0, var_0)
