# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import PY_074 as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    bool_0 = False
    var_0 = module_0.extend_blocks(bool_0)
    var_1 = module_0.extend_blocks(var_0)
    complex_0 = -589.26 - 1695j
    module_0.extend_blocks(complex_0, complex_0)


def test_case_1():
    none_type_0 = None
    var_0 = module_0.extend_blocks(none_type_0)


@pytest.mark.xfail(strict=True)
def test_case_2():
    str_0 = "u Q"
    tuple_0 = (str_0, str_0)
    module_0.extend_blocks(tuple_0, tuple_0)


@pytest.mark.xfail(strict=True)
def test_case_3():
    tuple_0 = ()
    var_0 = module_0.extend_blocks(tuple_0)
    bool_0 = True
    bytes_0 = b"\x9a\x8d4\xd1q8SD4\x94\xa1\xce\xdb\xc0e'r;\xba\xb9"
    var_1 = module_0.extend_blocks(bool_0)
    list_0 = [bool_0, bytes_0, bool_0, var_1]
    var_2 = module_0.extend_blocks(list_0)
    var_3 = module_0.extend_blocks(list_0)
    var_4 = module_0.extend_blocks(var_0)
    module_0.extend_blocks(bool_0, bool_0)
