# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import PY_028 as module_0


def test_case_0():
    none_type_0 = None
    module_0.fit(none_type_0)


def test_case_1():
    int_0 = 837
    none_type_0 = None
    module_0.fit(int_0, none_type_0)
