# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import PY_051 as module_0
import builtins as module_1


@pytest.mark.xfail(strict=True)
def test_case_0():
    bytes_0 = b"\xb6\xf9\x93\xa0\x13\x7ft\x82"
    module_0.compute_discount(bytes_0, bytes_0, bytes_0)


def test_case_1():
    bool_0 = True
    var_0 = module_0.compute_discount(bool_0, bool_0, is_first_order=bool_0)
    assert var_0 == pytest.approx(0.95, abs=0.01, rel=0.01)


@pytest.mark.xfail(strict=True)
def test_case_2():
    str_0 = "+"
    module_0.compute_discount(str_0, str_0)


@pytest.mark.xfail(strict=True)
def test_case_3():
    str_0 = "OJ$SoQ"
    module_0.compute_discount(str_0, str_0, str_0)


@pytest.mark.xfail(strict=True)
def test_case_4():
    str_0 = "bronze"
    object_0 = module_1.object()
    module_0.compute_discount(str_0, str_0, str_0, object_0)


@pytest.mark.xfail(strict=True)
def test_case_5():
    str_0 = "gold"
    none_type_0 = None
    module_0.compute_discount(none_type_0, str_0)


@pytest.mark.xfail(strict=True)
def test_case_6():
    bool_0 = False
    str_0 = "silver"
    var_0 = module_0.compute_discount(bool_0, bool_0, str_0, bool_0)
    var_1 = module_0.compute_discount(bool_0, str_0, is_first_order=str_0)
    assert var_1 == pytest.approx(0.0, abs=0.01, rel=0.01)
    set_0 = {str_0, var_1, str_0, str_0, str_0}
    module_0.compute_discount(set_0, set_0)
