# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import PY_052 as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    list_0 = []
    var_0 = module_0.validate_password(
        list_0, require_digit=list_0, require_special=list_0
    )
    none_type_0 = None
    module_0.validate_password(none_type_0, require_upper=none_type_0)


def test_case_1():
    str_0 = "((AEYsi9TI7m^azj"
    var_0 = module_0.validate_password(
        str_0, require_digit=str_0, require_special=str_0
    )
    assert var_0 is True


def test_case_2():
    set_0 = set()
    dict_0 = {}
    bool_0 = True
    var_0 = module_0.validate_password(dict_0, require_upper=bool_0)
    var_1 = module_0.validate_password(set_0, var_0)


@pytest.mark.xfail(strict=True)
def test_case_3():
    bool_0 = True
    module_0.validate_password(bool_0, require_digit=bool_0)


@pytest.mark.xfail(strict=True)
def test_case_4():
    str_0 = "((AEYsi9TI7m^zj"
    var_0 = module_0.validate_password(
        str_0, require_upper=str_0, require_special=str_0
    )
    assert var_0 is True
    set_0 = set()
    var_1 = module_0.validate_password(set_0, require_upper=set_0)
    var_2 = module_0.validate_password(str_0, require_digit=str_0, require_upper=var_1)
    assert var_2 is True
    var_3 = module_0.validate_password(
        str_0, require_digit=str_0, require_special=str_0
    )
    assert var_3 is True
    module_0.validate_password(var_1)


@pytest.mark.xfail(strict=True)
def test_case_5():
    str_0 = ".8^H,@?Qv5&"
    var_0 = module_0.validate_password(str_0)
    assert var_0 is True
    int_0 = 14
    module_0.validate_password(var_0, int_0, require_upper=str_0)


@pytest.mark.xfail(strict=True)
def test_case_6():
    str_0 = "((AEYsi9TI7m^zj"
    none_type_0 = None
    var_0 = module_0.validate_password(str_0, require_digit=none_type_0)
    assert var_0 is True
    set_0 = {none_type_0, none_type_0, none_type_0}
    var_1 = module_0.validate_password(set_0, require_upper=set_0)
    assert var_1 is False
    var_2 = module_0.validate_password(
        str_0, require_digit=str_0, require_special=str_0
    )
    assert var_2 is True
    var_3 = module_0.validate_password(str_0, require_special=var_2)
    assert var_3 is True
    module_0.validate_password(var_2, require_upper=set_0)


@pytest.mark.xfail(strict=True)
def test_case_7():
    bool_0 = False
    bytes_0 = b'\xb8\x07&t\x99\x7f\xbb\xb6\xb3"\xf1\xf6\xe7\x7f3\x03\x1c'
    dict_0 = {bytes_0: bytes_0, bytes_0: bytes_0, bytes_0: bytes_0}
    tuple_0 = (bool_0, bool_0, bytes_0, dict_0)
    var_0 = module_0.validate_password(
        tuple_0, require_digit=bool_0, require_special=dict_0
    )
    assert var_0 is False
    str_0 = "((AEYsi9TI7m^zj"
    var_1 = module_0.validate_password(str_0)
    assert var_1 is True
    none_type_0 = None
    var_2 = module_0.validate_password(str_0, require_digit=none_type_0)
    assert var_2 is True
    set_0 = {none_type_0, none_type_0, none_type_0}
    var_3 = module_0.validate_password(set_0, require_upper=set_0)
    var_4 = module_0.validate_password(dict_0, var_3, none_type_0)
    assert var_4 is False
    list_0 = [var_2, str_0]
    var_5 = module_0.validate_password(list_0)
    var_6 = module_0.validate_password(
        str_0, require_digit=str_0, require_upper=none_type_0
    )
    assert var_6 is True
    module_0.validate_password(tuple_0, bytes_0)
