# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import PY_053 as module_0


def test_case_0():
    int_0 = -700
    var_0 = module_0.calculate_shipping(int_0, int_0, fragile=int_0)
    assert var_0 == pytest.approx(8.0, abs=0.01, rel=0.01)
    var_1 = module_0.calculate_shipping(int_0, var_0)
    assert var_1 == pytest.approx(5.0, abs=0.01, rel=0.01)
    list_0 = module_0.calculate_shipping(int_0, var_1, var_1, country=var_1)
    assert list_0 == pytest.approx(7.5, abs=0.01, rel=0.01)
    var_2 = module_0.calculate_shipping(list_0, var_1, int_0)
    assert var_2 == pytest.approx(22.12, abs=0.01, rel=0.01)


def test_case_1():
    bool_0 = False
    var_0 = module_0.calculate_shipping(bool_0, bool_0)
    assert var_0 == pytest.approx(5.0, abs=0.01, rel=0.01)


@pytest.mark.xfail(strict=True)
def test_case_2():
    int_0 = 583
    var_0 = module_0.calculate_shipping(int_0, int_0)
    assert var_0 == pytest.approx(200.0, abs=0.01, rel=0.01)
    var_1 = module_0.calculate_shipping(var_0, int_0, country=int_0)
    assert var_1 == pytest.approx(200.0, abs=0.01, rel=0.01)
    str_0 = "AH),g+!H^\r"
    module_0.calculate_shipping(str_0, var_1, var_0)


def test_case_3():
    bool_0 = True
    var_0 = module_0.calculate_shipping(bool_0, bool_0, fragile=bool_0)
    assert var_0 == pytest.approx(8.0, abs=0.01, rel=0.01)
    var_1 = module_0.calculate_shipping(bool_0, var_0, country=bool_0)
    assert var_1 == pytest.approx(5.0, abs=0.01, rel=0.01)
    var_2 = module_0.calculate_shipping(var_1, var_1)
    assert var_2 == pytest.approx(11.0, abs=0.01, rel=0.01)


def test_case_4():
    bool_0 = True
    var_0 = module_0.calculate_shipping(bool_0, bool_0, fragile=bool_0)
    assert var_0 == pytest.approx(8.0, abs=0.01, rel=0.01)


def test_case_5():
    int_0 = -1655
    var_0 = module_0.calculate_shipping(int_0, int_0)
    assert var_0 == pytest.approx(5.0, abs=0.01, rel=0.01)
    var_1 = module_0.calculate_shipping(var_0, int_0, int_0)
    assert var_1 == pytest.approx(16.5, abs=0.01, rel=0.01)
    var_2 = module_0.calculate_shipping(var_0, int_0, var_0, int_0)
    assert var_2 == pytest.approx(19.5, abs=0.01, rel=0.01)
    int_1 = 3631
    var_3 = module_0.calculate_shipping(int_0, int_1)
    assert var_3 == pytest.approx(75.62, abs=0.01, rel=0.01)
    var_4 = module_0.calculate_shipping(var_1, var_0, var_3)
    assert var_4 == pytest.approx(42.38, abs=0.01, rel=0.01)
    none_type_0 = None
    var_5 = module_0.calculate_shipping(
        var_4, var_3, fragile=none_type_0, country=var_4
    )
    assert var_5 == pytest.approx(67.33, abs=0.01, rel=0.01)


@pytest.mark.xfail(strict=True)
def test_case_6():
    int_0 = -1655
    var_0 = module_0.calculate_shipping(int_0, int_0)
    assert var_0 == pytest.approx(5.0, abs=0.01, rel=0.01)
    var_1 = module_0.calculate_shipping(var_0, int_0)
    assert var_1 == pytest.approx(11.0, abs=0.01, rel=0.01)
    var_2 = module_0.calculate_shipping(var_0, var_0, var_0, country=var_1)
    assert var_2 == pytest.approx(16.5, abs=0.01, rel=0.01)
    var_3 = module_0.calculate_shipping(int_0, int_0)
    assert var_3 == pytest.approx(5.0, abs=0.01, rel=0.01)
    bool_0 = True
    str_0 = "international"
    var_4 = module_0.calculate_shipping(var_1, bool_0, fragile=int_0, country=str_0)
    assert var_4 == pytest.approx(46.0, abs=0.01, rel=0.01)
    module_0.calculate_shipping(str_0, var_0, country=var_4)
