# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import PY_060 as module_0
import builtins as module_1


def test_case_0():
    bool_0 = True
    str_0 = "\\\x0cP**S786kHO]@.&l<."
    var_0 = module_0.grade_exam(bool_0, bool_0, bool_0, bool_0, bool_0, str_0)
    assert var_0 == "F"


def test_case_1():
    bool_0 = False
    var_0 = module_0.grade_exam(bool_0, bool_0, bool_0, bool_0, bool_0, bool_0)
    assert var_0 == "F"
    int_0 = 429
    var_1 = module_0.grade_exam(int_0, int_0, int_0, int_0, int_0, int_0)
    assert var_1 == "B"


@pytest.mark.xfail(strict=True)
def test_case_2():
    str_0 = "y6X@18N[y[[Kd2B@NtM"
    complex_0 = -2266.63493 - 9j
    module_0.grade_exam(str_0, str_0, complex_0, complex_0, complex_0, str_0)


@pytest.mark.xfail(strict=True)
def test_case_3():
    none_type_0 = None
    module_0.grade_exam(
        none_type_0, none_type_0, none_type_0, none_type_0, none_type_0, none_type_0
    )


@pytest.mark.xfail(strict=True)
def test_case_4():
    float_0 = 2358.482017
    str_0 = ""
    var_0 = module_0.grade_exam(float_0, float_0, float_0, float_0, str_0, float_0)
    assert var_0 == "A"
    bool_0 = True
    float_1 = 1607.0
    var_1 = module_0.grade_exam(bool_0, bool_0, float_1, float_1, bool_0, float_1)
    assert var_1 == "B"
    bytes_0 = b""
    float_2 = -2054.0
    var_2 = module_0.grade_exam(bool_0, float_2, float_1, float_2, float_1, bool_0)
    assert var_2 == "F"
    var_3 = module_0.grade_exam(bool_0, float_1, bytes_0, bool_0, bytes_0, float_2)
    assert var_3 == "D"
    module_0.grade_exam(var_3, bool_0, var_1, float_1, var_1, var_3)


@pytest.mark.xfail(strict=True)
def test_case_5():
    int_0 = 489
    var_0 = module_0.grade_exam(int_0, int_0, int_0, int_0, int_0, int_0)
    assert var_0 == "B"
    var_1 = module_1.object()
    var_2 = module_0.grade_exam(int_0, int_0, int_0, int_0, int_0, int_0)
    assert var_2 == "B"
    dict_0 = {int_0: int_0, int_0: int_0}
    bool_0 = False
    module_0.grade_exam(dict_0, int_0, int_0, int_0, dict_0, bool_0)


@pytest.mark.xfail(strict=True)
def test_case_6():
    bool_0 = True
    int_0 = 222
    var_0 = module_0.grade_exam(bool_0, int_0, bool_0, bool_0, int_0, int_0)
    assert var_0 == "D"
    none_type_0 = None
    bytes_0 = b"\xe0b\xdb\xc4\xc2z\xc6\xce\xd4[\xc5\xd61\x86U"
    module_0.grade_exam(none_type_0, bytes_0, none_type_0, bytes_0, bytes_0, bool_0)


@pytest.mark.xfail(strict=True)
def test_case_7():
    bool_0 = True
    none_type_0 = None
    var_0 = module_0.grade_exam(
        bool_0, bool_0, bool_0, bool_0, none_type_0, none_type_0
    )
    assert var_0 == "F"
    object_0 = module_1.object()
    var_1 = module_1.object()
    int_0 = 68
    var_2 = module_0.grade_exam(int_0, int_0, int_0, int_0, int_0, int_0)
    assert var_2 == "B"
    module_1.object(**bool_0)


@pytest.mark.xfail(strict=True)
def test_case_8():
    bool_0 = True
    none_type_0 = None
    var_0 = module_0.grade_exam(
        bool_0, bool_0, bool_0, bool_0, none_type_0, none_type_0
    )
    assert var_0 == "F"
    var_1 = module_0.grade_exam(bool_0, bool_0, bool_0, bool_0, bool_0, bool_0)
    assert var_1 == "F"
    bool_1 = True
    var_2 = module_0.grade_exam(bool_0, bool_0, none_type_0, bool_0, bool_1, bool_1)
    assert var_2 == "F"
    int_0 = 80
    var_3 = module_0.grade_exam(int_0, int_0, int_0, int_0, int_0, int_0)
    assert var_3 == "B"
    object_0 = module_1.object()
    var_4 = module_0.grade_exam(int_0, bool_0, var_2, bool_0, var_3, int_0)
    assert var_4 == "C"
    module_1.object(*var_3)
