# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import PY_065 as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    bool_0 = True
    dict_0 = {bool_0: bool_0, bool_0: bool_0, bool_0: bool_0, bool_0: bool_0}
    module_0.assign_seat(dict_0, bool_0, dict_0, dict_0, dict_0)


@pytest.mark.xfail(strict=True)
def test_case_1():
    bytes_0 = b"_\xd0"
    none_type_0 = None
    module_0.assign_seat(bytes_0, bytes_0, none_type_0, none_type_0, none_type_0)


@pytest.mark.xfail(strict=True)
def test_case_2():
    bool_0 = False
    dict_0 = {bool_0: bool_0, bool_0: bool_0, bool_0: bool_0}
    module_0.assign_seat(bool_0, dict_0, bool_0, dict_0, bool_0)


@pytest.mark.xfail(strict=True)
def test_case_3():
    dict_0 = {}
    float_0 = 2760.005186848146
    module_0.assign_seat(dict_0, dict_0, float_0, float_0, float_0)


def test_case_4():
    dict_0 = {}
    float_0 = -3712.251
    var_0 = module_0.assign_seat(float_0, dict_0, dict_0, dict_0, float_0)


def test_case_5():
    dict_0 = {}
    float_0 = 2789.032192242243
    var_0 = module_0.assign_seat(float_0, dict_0, dict_0, dict_0, float_0)


@pytest.mark.xfail(strict=True)
def test_case_6():
    dict_0 = {}
    float_0 = 1.1
    tuple_0 = (dict_0,)
    module_0.assign_seat(tuple_0, tuple_0, float_0, float_0, float_0)


@pytest.mark.xfail(strict=True)
def test_case_7():
    dict_0 = {}
    float_0 = 1037.9899954801783
    tuple_0 = (dict_0, float_0)
    module_0.assign_seat(tuple_0, tuple_0, float_0, tuple_0, float_0)


def test_case_8():
    bool_0 = False
    dict_0 = {bool_0: bool_0, bool_0: bool_0, bool_0: bool_0, bool_0: bool_0}
    var_0 = module_0.assign_seat(dict_0, dict_0, dict_0, bool_0, bool_0)
    assert var_0 is False
