# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import PY_069 as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    str_0 = "T!3NH\\]P"
    module_0.apply_axis_properties(str_0, str_0, str_0)


def test_case_1():
    complex_0 = 1608.5 + 4337j
    var_0 = module_0.apply_axis_properties(complex_0, complex_0)
