# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import PY_057 as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    str_0 = "djdlVXEQf'J\x0bqVDXxf"
    none_type_0 = None
    set_0 = set()
    var_0 = module_0.parse_csv_line(set_0, trim_whitespace=set_0)
    var_1 = module_0.parse_csv_line(
        str_0, quote_char=str_0, trim_whitespace=none_type_0
    )
    var_2 = module_0.parse_csv_line(str_0, quote_char=str_0, skip_empty=str_0)
    module_0.parse_csv_line(none_type_0)


@pytest.mark.xfail(strict=True)
def test_case_1():
    list_0 = []
    var_0 = module_0.parse_csv_line(list_0, quote_char=list_0, skip_empty=list_0)
    none_type_0 = None
    module_0.parse_csv_line(none_type_0, trim_whitespace=none_type_0)


@pytest.mark.xfail(strict=True)
def test_case_2():
    bytes_0 = b" c\xd1@\xc5\xf6\xde\x8b"
    module_0.parse_csv_line(bytes_0, quote_char=bytes_0)


def test_case_3():
    str_0 = "hUar_I$}/P+v"
    var_0 = module_0.parse_csv_line(str_0, trim_whitespace=str_0)
    var_1 = module_0.parse_csv_line(str_0, skip_empty=str_0)
    set_0 = set()
    var_2 = module_0.parse_csv_line(set_0)
    set_1 = set()
    var_3 = module_0.parse_csv_line(set_1, set_1, skip_empty=set_1)
    var_4 = module_0.parse_csv_line(set_0, quote_char=var_3)
    none_type_0 = None
    var_5 = module_0.parse_csv_line(var_4, quote_char=none_type_0)
    var_6 = module_0.parse_csv_line(var_4, skip_empty=var_3)
    var_7 = module_0.parse_csv_line(var_2, var_1)
    var_8 = module_0.parse_csv_line(set_0, quote_char=str_0)
    none_type_1 = None
    var_9 = module_0.parse_csv_line(
        set_1, none_type_1, trim_whitespace=set_1, skip_empty=set_1
    )


@pytest.mark.xfail(strict=True)
def test_case_4():
    bool_0 = True
    module_0.parse_csv_line(bool_0, quote_char=bool_0)


@pytest.mark.xfail(strict=True)
def test_case_5():
    str_0 = '"\ra'
    var_0 = module_0.parse_csv_line(str_0)
    bytes_0 = b" c\xd1@\xc5\xf6\xde\x8b"
    module_0.parse_csv_line(bytes_0, skip_empty=bytes_0)


def test_case_6():
    bool_0 = False
    dict_0 = {bool_0: bool_0, bool_0: bool_0, bool_0: bool_0}
    var_0 = module_0.parse_csv_line(dict_0, bool_0)
    var_1 = module_0.parse_csv_line(var_0, var_0)
    var_2 = module_0.parse_csv_line(var_0, var_0)
    list_0 = []
    var_3 = module_0.parse_csv_line(list_0, quote_char=var_1, trim_whitespace=bool_0)


def test_case_7():
    str_0 = "wN{J8kA9'"
    list_0 = [str_0, str_0]
    var_0 = module_0.parse_csv_line(list_0, quote_char=str_0)


@pytest.mark.xfail(strict=True)
def test_case_8():
    list_0 = []
    none_type_0 = None
    var_0 = module_0.parse_csv_line(list_0, trim_whitespace=none_type_0)
    var_1 = module_0.parse_csv_line(list_0, trim_whitespace=none_type_0)
    var_2 = module_0.parse_csv_line(list_0, skip_empty=none_type_0)
    var_3 = module_0.parse_csv_line(list_0, skip_empty=var_0)
    var_4 = module_0.parse_csv_line(var_0, var_3, skip_empty=var_2)
    module_0.parse_csv_line(none_type_0, skip_empty=var_3)


def test_case_9():
    int_0 = 55
    list_0 = [int_0, int_0]
    var_0 = module_0.parse_csv_line(list_0, int_0, skip_empty=int_0)
    str_0 = "hUar_I$}/P+v"
    var_1 = module_0.parse_csv_line(str_0, trim_whitespace=str_0)
    var_2 = module_0.parse_csv_line(str_0, skip_empty=str_0)
    set_0 = set()
    var_3 = module_0.parse_csv_line(set_0)
    set_1 = set()
    var_4 = module_0.parse_csv_line(set_1, set_1, skip_empty=set_1)
    var_5 = module_0.parse_csv_line(var_3)
    var_6 = module_0.parse_csv_line(
        var_1, var_1, trim_whitespace=var_4, skip_empty=var_2
    )
    str_1 = "n'rIc^j/L,mU{\x0bm"
    var_7 = module_0.parse_csv_line(
        var_6, var_2, trim_whitespace=var_2, skip_empty=var_1
    )
    str_2 = "\x0c&*&4D#"
    var_8 = module_0.parse_csv_line(str_1, trim_whitespace=str_2)
    var_9 = module_0.parse_csv_line(str_1)
    var_10 = module_0.parse_csv_line(var_4, trim_whitespace=var_2, skip_empty=set_1)
    var_11 = module_0.parse_csv_line(var_5, quote_char=var_8)
    var_12 = module_0.parse_csv_line(var_7, var_11, var_1)
    var_13 = module_0.parse_csv_line(var_1, quote_char=var_7, trim_whitespace=var_11)
    var_14 = module_0.parse_csv_line(var_1, trim_whitespace=str_2)


@pytest.mark.xfail(strict=True)
def test_case_10():
    str_0 = "}h8,KpQ(-31HX"
    var_0 = module_0.parse_csv_line(str_0, trim_whitespace=str_0, skip_empty=str_0)
    bool_0 = False
    module_0.parse_csv_line(bool_0)


def test_case_11():
    str_0 = "wN{J8kA9'"
    list_0 = [str_0, str_0, str_0]
    list_1 = [str_0, str_0]
    tuple_0 = ()
    var_0 = module_0.parse_csv_line(list_1, quote_char=str_0)
    var_1 = module_0.parse_csv_line(tuple_0)
    var_2 = module_0.parse_csv_line(var_0, var_1, var_0)
    var_3 = module_0.parse_csv_line(var_0, tuple_0)
    bytes_0 = b"7\xc1\x07W\xb9\xd4\x9fo\xddm\xc8\xba\xed\xbc\xc0\x0e\xce\x1b"
    set_0 = {bytes_0, tuple_0}
    bool_0 = False
    var_4 = module_0.parse_csv_line(str_0, trim_whitespace=set_0, skip_empty=bool_0)
    var_5 = module_0.parse_csv_line(tuple_0, var_1)
    var_6 = module_0.parse_csv_line(list_1, var_1)
    var_7 = module_0.parse_csv_line(str_0, quote_char=list_1, skip_empty=tuple_0)
    var_8 = module_0.parse_csv_line(list_1, var_7)
    var_9 = module_0.parse_csv_line(var_3)
    var_10 = module_0.parse_csv_line(list_0, quote_char=str_0, skip_empty=var_8)
    var_11 = module_0.parse_csv_line(str_0, list_1)


@pytest.mark.xfail(strict=True)
def test_case_12():
    str_0 = "wN{J8kA9'"
    list_0 = [str_0, str_0, str_0]
    var_0 = module_0.parse_csv_line(list_0, skip_empty=str_0)
    list_1 = [str_0, str_0, var_0, str_0]
    module_0.parse_csv_line(list_1, quote_char=str_0)
