# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import PY_081 as module_0
import builtins as module_1


def test_case_0():
    none_type_0 = None
    with pytest.raises(ValueError):
        module_0.trigger(none_type_0, continuous=none_type_0)


def test_case_1():
    none_type_0 = None
    object_0 = module_1.object()
    with pytest.raises(ValueError):
        module_0.trigger(none_type_0, none_type_0, object_0)


@pytest.mark.xfail(strict=True)
def test_case_2():
    str_0 = "OEB _"
    module_0.trigger(continuous=str_0)


@pytest.mark.xfail(strict=True)
def test_case_3():
    str_0 = "u3(e@Z \n-`q"
    module_0.trigger(str_0, str_0)


def test_case_4():
    int_0 = 1300
    with pytest.raises(ValueError):
        module_0.trigger(int_0, int_0)


def test_case_5():
    str_0 = "mIXp?7Oi"
    with pytest.raises(ValueError):
        module_0.trigger(str_0, str_0, str_0)


@pytest.mark.xfail(strict=True)
def test_case_6():
    str_0 = "; UpT-"
    module_0.trigger(str_0, continuous=str_0)


def test_case_7():
    bool_0 = True
    with pytest.raises(ValueError):
        module_0.trigger(bool_0, continuous=bool_0)


def test_case_8():
    str_0 = ""
    with pytest.raises(ValueError):
        module_0.trigger(str_0, continuous=str_0)


def test_case_9():
    str_0 = ""
    none_type_0 = None
    with pytest.raises(ValueError):
        module_0.trigger(none_type_0, str_0)
