# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import PY_050 as module_0


def test_case_0():
    tuple_0 = ()
    var_0 = module_0.schedule_tasks(tuple_0)


@pytest.mark.xfail(strict=True)
def test_case_1():
    none_type_0 = None
    module_0.schedule_tasks(none_type_0)


@pytest.mark.xfail(strict=True)
def test_case_2():
    tuple_0 = ()
    var_0 = module_0.schedule_tasks(tuple_0)
    module_0.schedule_tasks(var_0)


def test_case_3():
    dict_0 = {}
    tuple_0 = (dict_0,)
    var_0 = module_0.schedule_tasks(tuple_0)


@pytest.mark.xfail(strict=True)
def test_case_4():
    dict_0 = {}
    list_0 = [dict_0, dict_0]
    var_0 = module_0.schedule_tasks(list_0)
    module_0.schedule_tasks(list_0, dict_0)
