# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import PY_062 as module_0
import builtins as module_1


@pytest.mark.xfail(strict=True)
def test_case_0():
    bool_0 = True
    list_0 = [bool_0, bool_0]
    module_0.validate_form_submission(list_0, list_0, bool_0, list_0)


@pytest.mark.xfail(strict=True)
def test_case_1():
    bytes_0 = b";\xfa~\xf7\\\tG"
    none_type_0 = None
    module_0.validate_form_submission(bytes_0, none_type_0, bytes_0, none_type_0)


@pytest.mark.xfail(strict=True)
def test_case_2():
    int_0 = 155
    list_0 = [int_0]
    str_0 = "83q,XWv^:"
    tuple_0 = (list_0, list_0, str_0)
    none_type_0 = None
    module_0.validate_form_submission(tuple_0, list_0, none_type_0, tuple_0)


@pytest.mark.xfail(strict=True)
def test_case_3():
    dict_0 = {}
    int_0 = -1583
    var_0 = module_0.validate_form_submission(dict_0, dict_0, int_0, dict_0)
    module_0.validate_form_submission(var_0, int_0, var_0, var_0)


@pytest.mark.xfail(strict=True)
def test_case_4():
    bytes_0 = b""
    dict_0 = {bytes_0: bytes_0, bytes_0: bytes_0, bytes_0: bytes_0, bytes_0: bytes_0}
    none_type_0 = None
    module_0.validate_form_submission(dict_0, dict_0, dict_0, none_type_0)


@pytest.mark.xfail(strict=True)
def test_case_5():
    bytes_0 = b"\x98\xd8\xda"
    dict_0 = {bytes_0: bytes_0, bytes_0: bytes_0, bytes_0: bytes_0, bytes_0: bytes_0}
    none_type_0 = None
    module_0.validate_form_submission(dict_0, dict_0, dict_0, none_type_0)


@pytest.mark.xfail(strict=True)
def test_case_6():
    dict_0 = {}
    float_0 = -296.0534348434714
    str_0 = "ma=7"
    dict_1 = {float_0: float_0, str_0: dict_0, float_0: dict_0}
    var_0 = module_0.validate_form_submission(dict_1, str_0, dict_1, dict_1)
    var_1 = module_0.validate_form_submission(dict_1, var_0, var_0, dict_0)
    bool_0 = False
    module_0.validate_form_submission(bool_0, var_1, bool_0, str_0)


@pytest.mark.xfail(strict=True)
def test_case_7():
    dict_0 = {}
    float_0 = -296.0534348434714
    str_0 = "ma=7"
    dict_1 = {float_0: float_0, str_0: dict_0, float_0: dict_0}
    var_0 = module_0.validate_form_submission(dict_1, dict_1, dict_1, dict_0)
    bool_0 = True
    module_0.validate_form_submission(bool_0, float_0, str_0, bool_0)


@pytest.mark.xfail(strict=True)
def test_case_8():
    tuple_0 = ()
    dict_0 = {tuple_0: tuple_0, tuple_0: tuple_0, tuple_0: tuple_0, tuple_0: tuple_0}
    var_0 = module_0.validate_form_submission(dict_0, tuple_0, dict_0, dict_0)
    str_0 = "Ue025[I`*H#F P7h@H&-"
    dict_1 = {tuple_0: tuple_0, str_0: tuple_0}
    module_1.object(**dict_1)


@pytest.mark.xfail(strict=True)
def test_case_9():
    str_0 = "dNl8p{kkT9x5<H2"
    str_1 = "ku\x0bf.xTyCZt'"
    str_2 = "C\n?5e%qREY4.C3{"
    dict_0 = {str_0: str_0, str_1: str_0, str_0: str_0, str_2: str_0}
    module_0.validate_form_submission(dict_0, dict_0, str_1, dict_0)
