# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import PY_078 as module_0


def test_case_0():
    dict_0 = {}
    var_0 = module_0.is_uniform_join_units(dict_0)
    assert var_0 is False


@pytest.mark.xfail(strict=True)
def test_case_1():
    bytes_0 = b"L0&\x84\xc3=\xe6\x0e\xce\xdb\xcd\xcf\x99g\xa9Q\xae#\xb8\x06"
    module_0.is_uniform_join_units(bytes_0)


@pytest.mark.xfail(strict=True)
def test_case_2():
    none_type_0 = None
    module_0.is_uniform_join_units(none_type_0)
