# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import PY_070 as module_0
import builtins as module_1


def test_case_0():
    str_0 = "\x0brHJ"
    bytes_0 = b"5"
    with pytest.raises(ValueError):
        module_0.construction_error(bytes_0, bytes_0, str_0)


def test_case_1():
    bool_0 = False
    str_0 = "\x0brwHJ"
    bytes_0 = b"ln\xaa\xf2\x13\xa8"
    with pytest.raises(ValueError):
        module_0.construction_error(bool_0, bytes_0, str_0)


@pytest.mark.xfail(strict=True)
def test_case_2():
    float_0 = -2421.0
    module_0.construction_error(float_0, float_0, float_0)


@pytest.mark.xfail(strict=True)
def test_case_3():
    bool_0 = True
    str_0 = "~"
    bytes_0 = b""
    module_0.construction_error(bool_0, bytes_0, str_0)


def test_case_4():
    bool_0 = False
    object_0 = module_1.object()
    str_0 = "\x0brwHJ"
    bytes_0 = b"\x00\xc4"
    with pytest.raises(ValueError):
        module_0.construction_error(bool_0, bytes_0, str_0)


@pytest.mark.xfail(strict=True)
def test_case_5():
    bool_0 = True
    str_0 = "~"
    bytes_0 = b""
    module_0.construction_error(bool_0, bytes_0, str_0, str_0)
