# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import PY_063 as module_0
import builtins as module_1


def test_case_0():
    bool_0 = True
    str_0 = "sije"
    var_0 = module_0.compute_tax_bracket(bool_0, str_0, bool_0, bool_0, str_0)
    assert var_0 == pytest.approx(0.0, abs=0.01, rel=0.01)


def test_case_1():
    bool_0 = False
    str_0 = "rie"
    var_0 = module_0.compute_tax_bracket(bool_0, str_0, bool_0, bool_0, bool_0)


@pytest.mark.xfail(strict=True)
def test_case_2():
    bytes_0 = b"_\xd0"
    none_type_0 = None
    module_0.compute_tax_bracket(
        bytes_0, bytes_0, none_type_0, none_type_0, none_type_0
    )


def test_case_3():
    bool_0 = False
    var_0 = module_0.compute_tax_bracket(bool_0, bool_0, bool_0, bool_0, bool_0)
    str_0 = "rie"
    var_1 = module_0.compute_tax_bracket(bool_0, str_0, bool_0, bool_0, var_0)
    int_0 = 2893
    var_2 = module_0.compute_tax_bracket(int_0, var_0, var_0, var_0, int_0)
    assert var_2 == pytest.approx(264.67, abs=0.01, rel=0.01)


def test_case_4():
    bool_0 = True
    str_0 = "single"
    var_0 = module_0.compute_tax_bracket(bool_0, str_0, bool_0, bool_0, str_0)
    assert var_0 == pytest.approx(0.0, abs=0.01, rel=0.01)
    object_0 = module_1.object()
