# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import PY_076 as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    bytes_0 = b"S\xab\xbfv"
    module_0.preprocess_sgm(bytes_0, bytes_0)


def test_case_1():
    none_type_0 = None
    var_0 = module_0.preprocess_sgm(none_type_0, none_type_0)


def test_case_2():
    str_0 = "\rvEiU .dceb"
    var_0 = module_0.preprocess_sgm(str_0, str_0)
