# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import PY_023 as module_0


def test_case_0():
    none_type_0 = None
    var_0 = module_0.init_plot(none_type_0, none_type_0)
